/**
 * {{viewTitle}} View
 * Generated by Domma CLI
 */
export const {{viewName}}View = {
    templateUrl: 'js/views/templates/{{viewName}}.html',

    /**
     * Called before the view is rendered
     * Use this to fetch data, validate auth, etc.
     * @param {Object} params - Route parameters (e.g., {id: '123'} from /{{viewName}}/:id)
     */
    async onEnter(params) {
        console.log('{{viewTitle}} view entering with params:', params);
        // Example: await H.get('/api/{{viewName}}');
    },

    /**
     * Called after the view is mounted to the DOM
     * Use this to initialize components, bind events, etc.
     * @param {Object} $container - Domma-wrapped container element
     */
    onMount($container) {
        console.log('{{viewTitle}} view mounted');

        // Example: Initialize components
        // E.tooltip($container.find('[data-tooltip]'));

        // Example: Bind events
        // $container.find('#my-button').on('click', () => {
        //     E.toast('Button clicked!', {type: 'success'});
        // });
    },

    /**
     * Called when leaving the view
     * Use this to cleanup event listeners, timers, etc.
     */
    onLeave() {
        console.log('{{viewTitle}} view leaving');

        // Example: Cleanup
        // $container.find('#my-button').off('click');
    }
};
