/**
 * {{viewTitle}} View
 * Generated by Domma CLI
 */
export const {{viewName}}View = {
    template: `
        <section class="container py-6">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="display-2 mb-4">{{viewTitle}}</h1>
                    <p class="lead text-secondary mb-5">
                        This is the {{viewTitle}} page. Add your content here.
                    </p>

                    <div class="card shadow-lg">
                        <div class="card-body p-5">
                            <h2 class="h4 mb-3">Getting Started</h2>
                            <p>
                                Edit this view in <code>js/views/{{viewName}}.js</code> to customize the content,
                                layout, and functionality.
                            </p>

                            <h3 class="h5 mt-4 mb-2">Available Lifecycle Hooks:</h3>
                            <ul>
                                <li><strong>onEnter(params)</strong> - Called before rendering (async supported)</li>
                                <li><strong>onMount($container)</strong> - Called after view is rendered</li>
                                <li><strong>onLeave()</strong> - Called when leaving view (cleanup)</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    `,

    /**
     * Called before the view is rendered
     * Use this to fetch data, validate auth, etc.
     * @param {Object} params - Route parameters (e.g., {id: '123'} from /{{viewName}}/:id)
     */
    async onEnter(params) {
        console.log('{{viewTitle}} view entering with params:', params);
        // Example: await H.get('/api/{{viewName}}');
    },

    /**
     * Called after the view is mounted to the DOM
     * Use this to initialize components, bind events, etc.
     * @param {Object} $container - Domma-wrapped container element
     */
    onMount($container) {
        console.log('{{viewTitle}} view mounted');

        // Example: Initialize components
        // E.tooltip($container.find('[data-tooltip]'));

        // Example: Bind events
        // $container.find('#my-button').on('click', () => {
        //     E.toast('Button clicked!', {type: 'success'});
        // });
    },

    /**
     * Called when leaving the view
     * Use this to cleanup event listeners, timers, etc.
     */
    onLeave() {
        console.log('{{viewTitle}} view leaving');

        // Example: Cleanup
        // $container.find('#my-button').off('click');
    }
};
